#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""make_demo_data_packages.py — wrap the sample data into MESA import packages.

MESA imports a project via **Manage data → Restore backup**, which reads a zip
whose members are `config.ini`, `input/...`, and `output/...` (anything else in
the zip is ignored on restore — see mesa.create_backup_archive / restore_backup_archive).

This tool turns each theme under `sample_data/` (built by make_sample_packages.py)
into one such zip, so the demo data can be published *separately* from the packaged
software and loaded with Restore backup. Packages are INPUTS ONLY — no processed
output — so a recipient runs the normal workflow:

    Restore backup  →  Assets ▸ Import assets  →  Parameters ▸ Load from Excel
    (pick input/<theme>_vulnerability.xlsx)  →  Process

Each zip contains:
    config.ini                            MESA defaults (so Restore has a config to land)
    input/asset/<theme>.gpkg              one layer per asset group (the geometry)
    input/<theme>_vulnerability.xlsx      importance/susceptibility per group (the
                                          'vulnerability' sheet processing_setup reads)
    README.txt                            human-facing import steps (ignored by Restore)

Run:  python devtools/make_demo_data_packages.py
      python devtools/make_demo_data_packages.py --out some/dir   (default: dist/demo_data)

NOTE: Restore backup REPLACES the current project's input/ + output/ + config.ini.
Restore a demo into a fresh/dedicated MESA copy (or accept that it overwrites).
"""
from __future__ import annotations

import argparse
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAMPLE_DIR = ROOT / "sample_data"
CONFIG_INI = ROOT / "config.ini"
DEFAULT_OUT = ROOT / "dist" / "demo_data"


def _themes() -> list[tuple[str, Path, Path]]:
    """(theme, gpkg, settings.xlsx) for every sample_data subfolder that has both."""
    out = []
    if not SAMPLE_DIR.is_dir():
        return out
    for sub in sorted(p for p in SAMPLE_DIR.iterdir() if p.is_dir()):
        gpkg = sub / f"{sub.name}.gpkg"
        xlsx = sub / "settings.xlsx"
        if gpkg.is_file() and xlsx.is_file():
            out.append((sub.name, gpkg, xlsx))
    return out


def _region(theme_dir: Path) -> str:
    """Pull the 'Region: ...' line from the theme README, if present (cosmetic)."""
    readme = theme_dir / "README.md"
    if readme.is_file():
        for line in readme.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.lower().startswith("region:"):
                return line.split(":", 1)[1].replace("*", "").strip()
    return ""


def _readme_text(theme: str, region: str) -> str:
    vuln = f"input/{theme}_vulnerability.xlsx"
    pretty = theme.replace("_", " ")
    return (
        f"MESA demo data package - {pretty}\n"
        + (f"Region: {region}\n" if region else "")
        + "\n"
        "Synthetic, deliberately overlapping asset data for trying MESA end to end.\n"
        "INPUTS ONLY - no processed results are included.\n"
        "\n"
        "How to load (MESA 5):\n"
        "  1. Manage data  >  Restore backup  >  pick this .zip.\n"
        "     (Restore REPLACES the current project's input/, output/ and config.ini -\n"
        "      use a fresh/dedicated MESA copy if you want to keep your current project.)\n"
        "  2. Assets  >  Import assets   (reads input/asset/" + theme + ".gpkg;\n"
        "     each GeoPackage layer becomes an asset group).\n"
        f"  3. Parameters  >  Load from Excel  >  pick {vuln}\n"
        "     (sets importance/susceptibility per group, matched on name_original).\n"
        "  4. Geocodes  >  build grids, then Process.  View in Maps / Report engine.\n"
        "\n"
        "Generated by devtools/make_demo_data_packages.py from sample_data/.\n"
    )


def build(out_dir: Path) -> None:
    themes = _themes()
    if not themes:
        print(f"No sample data found under {SAMPLE_DIR}. "
              f"Run 'python devtools/make_sample_packages.py' first.")
        return
    if not CONFIG_INI.is_file():
        print(f"Missing {CONFIG_INI} — cannot include a config.ini in the packages.")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    made = []
    for theme, gpkg, xlsx in themes:
        region = _region(gpkg.parent)
        zip_path = out_dir / f"mesa_demo_{theme}.zip"
        if zip_path.exists():
            zip_path.unlink()
        # ZIP_DEFLATED = universal (Windows Explorer can open it); matches the
        # default of mesa.create_backup_archive.
        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
            zf.write(CONFIG_INI, "config.ini")
            zf.write(gpkg, f"input/asset/{theme}.gpkg")
            zf.write(xlsx, f"input/{theme}_vulnerability.xlsx")
            zf.writestr("README.txt", _readme_text(theme, region))
        size_kb = zip_path.stat().st_size / 1024
        made.append((theme, zip_path, size_kb))
        print(f"[{theme}] -> {zip_path}  ({size_kb:.0f} KB)")

    print(f"\n{len(made)} demo package(s) written to {out_dir}")
    print("Each loads via MESA -> Manage data -> Restore backup (inputs only).")


def main() -> None:
    ap = argparse.ArgumentParser(description="Wrap sample_data themes into MESA import packages (Restore-backup zips).")
    ap.add_argument("--out", default=str(DEFAULT_OUT),
                    help=f"output directory for the zips (default: {DEFAULT_OUT})")
    args = ap.parse_args()
    build(Path(args.out))


if __name__ == "__main__":
    main()
